version: "3.8"

services:
  api:
    build: .
    container_name: orders-api
    restart: always
    ports:
      - "21401:21401"
    depends_on:
      - mongo
      - rabbitmq
    environment:
      NODE_ENV: production
      MONGO_URI: "mongodb://mongo:27017/test/orders"
      RABBITMQ_URL: "amqp://rabbitmq-orders:5672"
    networks:
      - app_network

  mongo:
    image: mongo:5
    container_name: mongodb-orders
    restart: always
    ports:
      - "27017:27017"
    networks:
      - app_network

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq-orders
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app_network

  prometheus:
    image: prom/prometheus
    container_name: prometheus-orders
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9099:9099"
    networks:
      - app_network

  grafana:
    image: grafana/grafana
    container_name: grafana-orders
    ports:
      - "3002:3002"
    networks:
      - app_network
networks:
  app_network:
    driver: bridge
